/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Texture } from "../../texture/base/Texture";
import { Folder } from "../../folder/base/Folder";
import { EnumFileFormat } from "./EnumFileFormat";

@ObjectType()
class File {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeField!: string | null;

  @ApiProperty({
    required: false,
    type: () => Texture,
  })
  @ValidateNested()
  @Type(() => Texture)
  @IsOptional()
  texture?: Texture | null;

  @ApiProperty({
    required: false,
    type: () => Folder,
  })
  @ValidateNested()
  @Type(() => Folder)
  @IsOptional()
  folder?: Folder | null;

  @ApiProperty({
    required: false,
    enum: EnumFileFormat,
  })
  @IsEnum(EnumFileFormat)
  @IsOptional()
  @Field(() => EnumFileFormat, {
    nullable: true,
  })
  format?: "Option1" | null;
}

export { File as File };
