import { registerEnumType } from "@nestjs/graphql";

export enum FileFormat {
    Anc = ".anc",
    Anm = ".anm",
    Ann = ".ann",
    Bin = ".bin",
    Bk2 = ".bk2",
    Bnk = ".bnk",
    Bshd = ".bshd",
    Chroma = ".chroma",
    Clc = ".clc",
    Clm = ".clm",
    Cln = ".cln",
    Cur = ".cur",
    Dae = ".dae",
    Dat = ".dat",
    Data = ".data",
    Dds = ".dds",
    Div = ".div",
    Fbx = ".fbx",
    Ffxactor = ".ffxactor",
    Ffxbones = ".ffxbones",
    Ffxanim = ".ffxanim",
    Fnt = ".fnt",
    Gamescript = ".gamescript",
    Gr2 = ".gr2",
    Gtp = ".gtp",
    Gts = ".gts",
    Itemscript = ".itemscript",
    Jpg = ".jpg",
    Js = ".js",
    Json = ".json",
    Khn = ".khn",
    Loca = ".loca",
    Lsb = ".lsb",
    Lsbc = ".lsbc",
    Lsbs = ".lsbs",
    Lsf = ".lsf",
    Lsfx = ".lsfx",
    Lsj = ".lsj",
    Lsx = ".lsx",
    Meta = ".meta",
    Metal = ".metal",
    Ogg = ".ogg",
    Osi = ".osi",
    Otf = ".otf",
    Patch = ".patch",
    Png = ".png",
    Psd = ".psd",
    Psocache = ".psocache",
    Shd = ".shd",
    Tga = ".tga",
    Tmpl = ".tmpl",
    Ttf = ".ttf",
    Txt = ".txt",
    Wav = ".wav",
    Wem = ".wem",
    Xaml = ".xaml",
    Xml = ".xml"
}

registerEnumType(FileFormat, {
    name: "FileFormat",
  });