/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Folder } from "./Folder";
import { FolderCountArgs } from "./FolderCountArgs";
import { FolderFindManyArgs } from "./FolderFindManyArgs";
import { FolderFindUniqueArgs } from "./FolderFindUniqueArgs";
import { CreateFolderArgs } from "./CreateFolderArgs";
import { UpdateFolderArgs } from "./UpdateFolderArgs";
import { DeleteFolderArgs } from "./DeleteFolderArgs";
import { FileFindManyArgs } from "../../file/base/FileFindManyArgs";
import { File } from "../../file/base/File";
import { FolderService } from "../folder.service";
@graphql.Resolver(() => Folder)
export class FolderResolverBase {
  constructor(protected readonly service: FolderService) {}

  async _foldersMeta(
    @graphql.Args() args: FolderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Folder])
  async folders(@graphql.Args() args: FolderFindManyArgs): Promise<Folder[]> {
    return this.service.folders(args);
  }

  @graphql.Query(() => Folder, { nullable: true })
  async folder(
    @graphql.Args() args: FolderFindUniqueArgs
  ): Promise<Folder | null> {
    const result = await this.service.folder(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Folder)
  async createFolder(@graphql.Args() args: CreateFolderArgs): Promise<Folder> {
    return await this.service.createFolder({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Folder)
  async updateFolder(
    @graphql.Args() args: UpdateFolderArgs
  ): Promise<Folder | null> {
    try {
      return await this.service.updateFolder({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Folder)
  async deleteFolder(
    @graphql.Args() args: DeleteFolderArgs
  ): Promise<Folder | null> {
    try {
      return await this.service.deleteFolder(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [File], { name: "files" })
  async findFiles(
    @graphql.Parent() parent: Folder,
    @graphql.Args() args: FileFindManyArgs
  ): Promise<File[]> {
    const results = await this.service.findFiles(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
